[project]
name = "buzz_weekly_crew"
version = "0.1.0"
description = "Crew that gathers content to the Buzz Weekly blog"
authors = [
    { name = "Johan Uddståhl", email = "baktakt@gmail.com" },
]
requires-python = ">=3.10,<=3.13"
dependencies = [
    "crewai[tools]>=1.9.3",
    "feedparser>=6.0.11",
    "beautifulsoup4>=4.12.3",
]

[project.scripts]
buzz_weekly_crew = "buzz_weekly_crew.main:run"
train = "buzz_weekly_crew.main:train"
run_crew = "buzz_weekly_crew.main:run"

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"
